// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/csharp-client-dev/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r CsharpClientDev) MarshalJSON() ([]byte, error) {
	var concrete struct {
		OriginalWorkspace  *dagger.Directory
		Workspace          *dagger.Directory
		ClientDockerConfig *dagger.Secret
		Ws                 *dagger.Workspace
	}
	concrete.OriginalWorkspace = r.OriginalWorkspace
	concrete.Workspace = r.Workspace
	concrete.ClientDockerConfig = r.ClientDockerConfig
	concrete.Ws = r.Ws
	return json.Marshal(&concrete)
}

func (r *CsharpClientDev) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		OriginalWorkspace  *dagger.Directory
		Workspace          *dagger.Directory
		ClientDockerConfig *dagger.Secret
		Ws                 *dagger.Workspace
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.OriginalWorkspace = concrete.OriginalWorkspace
	r.Workspace = concrete.Workspace
	r.ClientDockerConfig = concrete.ClientDockerConfig
	r.Ws = concrete.Ws
	return nil
}

func main() {
	ctx := context.Background()

	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}

func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
	))
	defer telemetry.Close()

	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}

func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "CsharpClientDev":
		switch fnName {
		case "DevContainer":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CsharpClientDev).DevContainer(&parent), nil
		case "Format":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CsharpClientDev).Format(&parent), nil
		case "Generate":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CsharpClientDev).Generate(&parent, ctx)
		case "Lint":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*CsharpClientDev).Lint(&parent, ctx)
		case "Pack":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var configuration string
			if inputArgs["configuration"] != nil {
				err = json.Unmarshal([]byte(inputArgs["configuration"]), &configuration)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg configuration", err))
				}
			}
			return (*CsharpClientDev).Pack(&parent, configuration), nil
		case "Publish":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var nugetToken *dagger.Secret
			if inputArgs["nugetToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nugetToken"]), &nugetToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nugetToken", err))
				}
			}
			var dryRun bool
			if inputArgs["dryRun"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dryRun"]), &dryRun)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dryRun", err))
				}
			}
			return nil, (*CsharpClientDev).Publish(&parent, ctx, version, nugetToken, dryRun)
		case "Source":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CsharpClientDev).Source(&parent), nil
		case "Test":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*CsharpClientDev).Test(&parent, ctx)
		case "":
			var parent CsharpClientDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspaceDir *dagger.Directory
			if inputArgs["workspaceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspaceDir"]), &workspaceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspaceDir", err))
				}
			}
			var clientDockerConfig *dagger.Secret
			if inputArgs["clientDockerConfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["clientDockerConfig"]), &clientDockerConfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg clientDockerConfig", err))
				}
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			return New(workspaceDir, clientDockerConfig, ws), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("Toolchain to develop the Dagger C# SDK (experimental).\n").
			WithObject(
				dag.TypeDef().WithObject("CsharpClientDev", dagger.TypeDefWithObjectOpts{Description: "Develop the Dagger C# SDK (experimental).", SourceMap: dag.SourceMap("main.go", 19, 6)}).
					WithFunction(
						dag.Function("DevContainer",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Return the C# SDK workspace mounted in a .NET SDK container,\nworking directory set to the SDK source.").
							WithSourceMap(dag.SourceMap("main.go", 54, 1))).
					WithFunction(
						dag.Function("Format",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Format all C# source files using csharpier.").
							WithSourceMap(dag.SourceMap("main.go", 102, 1))).
					WithFunction(
						dag.Function("Generate",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("Generate code from the engine introspection JSON.").
							WithSourceMap(dag.SourceMap("main.go", 70, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("Lint",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Lint all C# source files in the SDK using csharpier.").
							WithSourceMap(dag.SourceMap("main.go", 93, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("Pack",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Pack the Dagger.SDK into a NuGet package.").
							WithSourceMap(dag.SourceMap("main.go", 110, 1)).
							WithArg("configuration", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 113, 2), DefaultValue: dagger.JSON("\"Release\"")})).
					WithFunction(
						dag.Function("Publish",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Publish the Dagger.SDK to NuGet.").
							WithSourceMap(dag.SourceMap("main.go", 127, 1)).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 131, 2)}).
							WithArg("nugetToken", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 134, 2)}).
							WithArg("dryRun", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 137, 2)})).
					WithFunction(
						dag.Function("Source",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Source returns the source directory for the C# SDK.").
							WithSourceMap(dag.SourceMap("main.go", 65, 1))).
					WithFunction(
						dag.Function("Test",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Test the C# SDK.").
							WithSourceMap(dag.SourceMap("main.go", 79, 1)).
							WithCheck()).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("CsharpClientDev")).
							WithSourceMap(dag.SourceMap("main.go", 26, 1)).
							WithArg("workspaceDir", dag.TypeDef().WithObject("Directory").WithOptional(true), dagger.FunctionWithArgOpts{Description: "A directory with all the files needed to develop the SDK.", SourceMap: dag.SourceMap("main.go", 30, 2), DefaultPath: "/", Ignore: []string{"*", "!sdk/csharp/**", "sdk/csharp/**/bin/**", "sdk/csharp/**/obj/**", "sdk/csharp/examples/**"}}).
							WithArg("clientDockerConfig", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "A docker config file with credentials to install on clients.", SourceMap: dag.SourceMap("main.go", 33, 2)}).
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{Description: "Workspace forwarded to engine-dev for VCS stamping.", SourceMap: dag.SourceMap("main.go", 35, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
