using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Dagger.SDK.CodeGen.Extensions;
using Dagger.SDK.CodeGen.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Type = Dagger.SDK.CodeGen.Types.Type;

namespace Dagger.SDK.CodeGen.Code;

public class CodeRenderer : ICodeRenderer
{
    public string RenderPre()
    {
        return """
            // <auto-generated/>
            // Generated by the Dagger C# SDK code generator from engine
            // introspection. Do not edit; regenerate instead.
            #nullable enable

            using System.Collections.Immutable;
            using System.Text.Json.Serialization;
            using System.Threading;
            using System.Threading.Tasks;

            using Dagger.GraphQL;
            using Dagger.JsonConverters;

            namespace Dagger;
            """;
    }

    public string RenderEnum(Type type)
    {
        var enumValuesWithDocs = type.EnumValues.Select(ev =>
        {
            var doc = string.IsNullOrEmpty(ev.Description)
                ? $"/// <summary>{ev.Name}</summary>"
                : RenderSummaryDocComment(ev.Description);
            return $"{doc}\n{ev.Name}";
        });

        return $$"""
            {{RenderDocComment(type)}}
            {{RenderExperimental(type)}}
            [JsonConverter(typeof(JsonStringEnumConverter<{{Formatter.FormatType(type.Name)}}>))]
            public enum {{Formatter.FormatType(type.Name)}}
            {
                {{string.Join(",\n", enumValuesWithDocs)}}
            }
            """;
    }

    public string RenderInputObject(Type type)
    {
        var properties = type.InputFields.Select(field =>
            $$"""
            {{RenderDocComment(field)}}
            public {{field.Type.GetTypeName()}} {{Formatter.FormatProperty(
                field.Name
            )}} { get; } = {{field.GetVarName()}};
            """
        );

        var constructorFields = type.InputFields.Select(field =>
            $"{field.Type.GetTypeName()} {field.GetVarName()}"
        );

        var toKeyValuePairsProperties = type.InputFields.Select(field =>
            $"""
            kvPairs.Add(new KeyValuePair<string, Value>("{field.Name}", {RenderArgumentValue(
                field,
                asProperty: true
            )} as Value));
            """
        );

        var toKeyValuePairsMethod = $$"""
            /// <summary>
            /// Converts this input object to GraphQL key-value pairs.
            /// </summary>
            public List<KeyValuePair<string, Value>> ToKeyValuePairs()
            {
                var kvPairs = new List<KeyValuePair<string, Value>>();
                {{string.Join("\n", toKeyValuePairsProperties)}}
                return kvPairs;
            }
            """;

        return $$"""
            {{RenderDocComment(type)}}
            {{RenderExperimental(type)}}
            public struct {{Formatter.FormatType(type.Name)}}({{string.Join(
                ", ",
                constructorFields
            )}}) : IInputObject
            {
                {{string.Join("\n\n", properties)}}
                {{toKeyValuePairsMethod}}
            }
            """;
    }

    // Determines the C# method name for a field within a declaring type,
    // appending an underscore when it would collide with the type name.
    private static string FieldMethodName(Field field, string declaringTypeName)
    {
        var methodName = Formatter.FormatMethod(field.Name);
        if (declaringTypeName.Equals(field.Name, StringComparison.CurrentCultureIgnoreCase))
        {
            methodName = $"{methodName}_";
        }
        return methodName;
    }

    private static bool FieldIsAsync(Field field) =>
        (field.Type.IsLeaf() || field.Type.IsList()) && !field.Type.IsInterface();

    // Renders the parameter list for a field method (required + optional args,
    // plus a trailing CancellationToken for async methods).
    private static string RenderFieldParams(Field field)
    {
        var isAsync = FieldIsAsync(field);
        var args = field
            .RequiredArgs()
            .Select(RenderArgument)
            .Concat(field.OptionalArgs().Select(RenderOptionalArgument))
            .Concat(isAsync ? new[] { "CancellationToken cancellationToken = default" } : []);
        return string.Join(",", args);
    }

    // Renders a full field method (signature + query-building body). Shared by
    // object types and by interface wrapper classes so their signatures match.
    private string RenderFieldMethod(Field field, string declaringTypeName)
    {
        var methodName = FieldMethodName(field, declaringTypeName);
        return $$"""
            {{RenderDocComment(field)}}
            {{RenderExperimental(field, declaringTypeName)}}
            {{RenderObsolete(field)}}
            public {{RenderReturnType(field.Type)}} {{methodName}}({{RenderFieldParams(field)}})
            {
                {{RenderArgumentBuilder(field)}}
                {{RenderQueryBuilder(field)}}
                return {{RenderReturnValue(field)}};
            }
            """;
    }

    // Renders a field as an interface method signature (no body, no `async`
    // modifier), matching the corresponding wrapper/object method signature.
    private string RenderFieldSignature(Field field, string declaringTypeName)
    {
        var methodName = FieldMethodName(field, declaringTypeName);
        // Interface signatures omit the `async` modifier (an implementation detail).
        var returnType = RenderReturnType(field.Type);
        if (returnType.StartsWith("async "))
        {
            returnType = returnType["async ".Length..];
        }
        return $"""
            {RenderDocComment(field)}
            {returnType} {methodName}({RenderFieldParams(field)});
            """;
    }

    public string RenderObject(Type type)
    {
        var methods = type.Fields.Select(field => RenderFieldMethod(field, type.Name));

        // Generate `As{Interface}()` conversion helpers for every interface
        // this object implements (mirroring the Go client's AsNode etc.).
        // This is a local type conversion — no GraphQL call: an object's query
        // is valid wherever the interface is expected, so the conversion just
        // hands the same query to the interface's wrapper class.
        var interfaceConversionMethods =
            type.Interfaces?.Select(iface =>
            {
                var interfaceName = Formatter.FormatType(iface.Name);
                var wrapperName = $"{interfaceName}Wrapper";

                return $$"""
                /// <summary>
                /// Returns this object as a {{interfaceName}}.
                /// This is a local type conversion — no GraphQL call.
                /// </summary>
                public {{interfaceName}} As{{interfaceName}}()
                {
                    return new {{wrapperName}}(QueryBuilder, GraphQLClient);
                }
                """;
            }) ?? Enumerable.Empty<string>();

        var implementsIdInterface = "";
        if (type.Fields.Any(field => field.Name == "id"))
        {
            var idField = type.Fields.First(field => field.Name == "id");
            implementsIdInterface = $", IId<{idField.Type.GetTypeName()}>";
        }

        var allMethods = methods.Concat(interfaceConversionMethods);

        var className = Formatter.FormatType(type.Name);

        return $$"""
            {{RenderDocComment(type)}}
            {{RenderExperimental(type)}}
            public class {{className}}(QueryBuilder queryBuilder, GraphQLClient gqlClient) : Object(queryBuilder, gqlClient){{implementsIdInterface}}
            {
                {{string.Join("\n\n", allMethods)}}
            }
            """;
    }

    public string RenderScalar(Type type)
    {
        var t = Formatter.FormatType(type.Name);
        return $$"""
            {{RenderDocComment(type)}}
            {{RenderExperimental(type)}}
            [JsonConverter(typeof(ScalarIdConverter<{{t}}>))]
            public class {{Formatter.FormatType(t)}} : Scalar
            {
            }
            """;
    }

    public string Format(string source)
    {
        return CSharpSyntaxTree
            .ParseText(source)
            .GetRoot()
            .NormalizeWhitespace(eol: "\n")
            .ToFullString();
    }

    private static string RenderObsolete(Field field)
    {
        if (!field.IsDeprecated)
            return string.Empty;
        string escapedReason = SymbolDisplay.FormatLiteral(field.DeprecationReason, true);
        return $"[Obsolete({escapedReason})]";
    }

    /// <summary>
    /// Generates a unique diagnostic ID for an experimental API.
    /// Format: DAGGER_<TYPE>_<METHOD>
    /// Examples: DAGGER_DIRECTORY_WITHPATCH, DAGGER_MODULE_CHECKS
    /// </summary>
    private static string GenerateDiagnosticId(string typeName, string memberName)
    {
        return $"DAGGER_{typeName.ToUpperInvariant()}_{memberName.ToUpperInvariant()}";
    }

    private static string RenderExperimental(Field field, string typeName)
    {
        if (!field.Directives.IsExperimental())
            return string.Empty;

        var reason = field.Directives.GetExperimentalReason();
        var escapedReason = reason != null ? SymbolDisplay.FormatLiteral(reason, true) : null;

        // Generate unique diagnostic ID per API for granular warning control
        // Follows Microsoft best practices: <PREFIX><IDENTIFIER> format
        // Example: Directory.WithPatch -> DAGGER_DIR_WITHPATCH
        var diagnosticId = GenerateDiagnosticId(typeName, field.Name);

        if (escapedReason != null)
        {
            return $"[System.Diagnostics.CodeAnalysis.Experimental(\"{diagnosticId}\")]";
        }
        else
        {
            return $"[System.Diagnostics.CodeAnalysis.Experimental(\"{diagnosticId}\")]";
        }
    }

    private static string RenderExperimental(Type type)
    {
        if (!type.Directives.IsExperimental())
            return string.Empty;

        var reason = type.Directives.GetExperimentalReason();
        var escapedReason = reason != null ? SymbolDisplay.FormatLiteral(reason, true) : null;

        // For types (enums, objects, etc.), use just the type name
        // Example: ExperimentalModule -> DAGGER_EXPERIMENTALMODULE
        var diagnosticId = $"DAGGER_{type.Name.ToUpperInvariant()}";

        if (escapedReason != null)
        {
            return $"[System.Diagnostics.CodeAnalysis.Experimental(\"{diagnosticId}\")]";
        }
        else
        {
            return $"[System.Diagnostics.CodeAnalysis.Experimental(\"{diagnosticId}\")]";
        }
    }

    private static string RenderDocComment(Type type)
    {
        return RenderSummaryDocComment(type.Description, type.Name);
    }

    private static string RenderDocComment(Field field)
    {
        var builder = new StringBuilder();
        builder.AppendLine(RenderSummaryDocComment(field.Description, field.Name));
        builder = field.Args.Aggregate(
            builder,
            (sb, arg) =>
            {
                string[] lines = arg.Description.Split('\n');
                sb.AppendLine(
                    $"/// <param name=\"{System.Security.SecurityElement.Escape(arg.GetVarName())}\">"
                );
                foreach (var line in lines)
                {
                    sb.AppendLine($"/// {System.Security.SecurityElement.Escape(line)}");
                }

                sb.AppendLine($"/// </param>");
                return sb;
            }
        );

        // Add cancellationToken param doc for async methods
        var isAsync = (field.Type.IsLeaf() || field.Type.IsList()) && !field.Type.IsInterface();
        if (isAsync)
        {
            builder.AppendLine("/// <param name=\"cancellationToken\">");
            builder.AppendLine(
                "/// A cancellation token that can be used to cancel the operation."
            );
            builder.AppendLine("/// </param>");
        }

        return builder.ToString();
    }

    private static string RenderDocComment(InputValue field)
    {
        return RenderSummaryDocComment(field.Description, field.Name);
    }

    private static string RenderSummaryDocComment(string doc, string fallbackName = "")
    {
        string content;

        if (string.IsNullOrEmpty(doc))
        {
            // Provide a default summary based on the name if no description is available
            content = string.IsNullOrEmpty(fallbackName)
                ? "/// No description available."
                : $"/// {System.Security.SecurityElement.Escape(fallbackName)}";
        }
        else
        {
            var description = doc.Split('\n')
                .Select(line => $"/// {System.Security.SecurityElement.Escape(line)}")
                .Select(line => line.Trim());
            content = string.Join("\n", description);
        }

        return $"""
            /// <summary>
            {content}
            /// </summary>
            """;
    }

    private static string GetNormalizedTypeName(InputValue arg)
    {
        return GetNormalizedTypeName(arg.Type, arg.Name, arg.Directives);
    }

    private static string GetNormalizedTypeName(
        TypeRef typeRef,
        string name,
        Directive[]? directives = null
    )
    {
        var tr = typeRef.GetType_();
        if (tr.IsList())
        {
            return $"{GetNormalizedTypeName(tr.OfType, name, directives)}[]";
        }

        var type = tr.GetTypeName();

        // Object-typed arguments are represented in the schema as a generic `ID`
        // scalar carrying an @expectedType(name: "...") directive that names the
        // concrete object type (e.g. an argument of `[ID!]` for a list of
        // Container is annotated with @expectedType(name: "Container")). Recover
        // the concrete type from the directive rather than emitting the raw `ID`.
        if (tr.Name == "ID")
        {
            var expected = directives.GetDirective("expectedType")?.GetDirectiveArgument("name")
                ?.Trim('"');
            return string.IsNullOrEmpty(expected) ? type : Formatter.FormatType(expected);
        }

        // Legacy typed IDs (e.g. `ContainerID` -> `Container`) for older schemas
        // that predate the generic `ID` + @expectedType representation.
        if (type.EndsWith("Id") && !string.Equals(name, "id"))
        {
            type = type.Replace("Id", "");
        }

        return type;
    }

    private static string RenderArgument(InputValue arg)
    {
        return $"{GetNormalizedTypeName(arg)} {arg.GetVarName()}";
    }

    internal static string RenderOptionalArgument(InputValue arg)
    {
        var baseType = GetNormalizedTypeName(arg);
        var nullableType = baseType + "?";

        if (arg.DefaultValue != null)
        {
            // C# default parameter values must be compile-time constants, but a
            // list default is a collection expression (e.g. ["./..."]) which is
            // not constant. Emit `= null`; the engine applies the real default
            // server-side when the argument is omitted.
            if (arg.Type.IsList())
            {
                return $"{nullableType} {arg.GetVarName()} = null";
            }

            if (arg.Type.IsScalar() && string.IsNullOrWhiteSpace(arg.DefaultValue.Trim('"')))
            {
                return $"{nullableType} {arg.GetVarName()} = null";
            }

            // Enum defaults reference the GraphQL default literal (e.g. FAIL),
            // but the members generated from `enumValues` may not include that
            // literal (member sets can be engine-version-scoped views). Emit
            // `= null`; omitted args get the server-side default.
            if (arg.Type.IsEnum())
            {
                return $"{nullableType} {arg.GetVarName()} = null";
            }

            // For boolean types with non-null default values, use non-nullable type
            if (baseType == "bool" && (arg.DefaultValue == "true" || arg.DefaultValue == "false"))
            {
                return $"{baseType} {arg.GetVarName()} = {arg.DefaultValue}";
            }

            return $"{nullableType} {arg.GetVarName()} = {arg.DefaultValue}";
        }

        return $"{nullableType} {arg.GetVarName()} = null";
    }

    private static string RenderReturnType(TypeRef type)
    {
        if (type.IsLeaf() || type.IsList())
        {
            return $"async Task<{type.GetTypeName()}>";
        }

        return type.GetTypeName();
    }

    private static string RenderReturnValue(Field field)
    {
        var type = field.Type;

        if (type.IsLeaf())
        {
            return $"await QueryExecutor.ExecuteAsync<{field.Type.GetTypeName()}>(GraphQLClient, queryBuilder, cancellationToken)";
        }

        if (type.IsList() && type.GetType_().OfType.IsObject())
        {
            // Lists of objects are returned as their ids, then each element is
            // reconstructed lazily via the Relay-style `node(id:) { ... on T }`
            // lookup (the legacy per-type `loadTFromID` endpoints no longer
            // exist, and ids are the generic `ID` scalar).
            var typeName = type.GetType_().OfType.GetTypeName();
            return $"""
                (await QueryExecutor.ExecuteListAsync<Id>(GraphQLClient, queryBuilder, cancellationToken))
                    .Select(id =>
                        new {typeName}(
                            QueryBuilder.Builder()
                                .Select("node", ImmutableList.Create<Argument>(new Argument("id", new StringValue(id.Value))))
                                .Select("... on {typeName}"),
                            GraphQLClient
                        )
                    )
                    .ToArray()
                """;
        }

        if (type.IsList() && type.GetType_().OfType.IsScalar())
        {
            var typeName = type.GetType_().OfType.GetTypeName();
            return $"await QueryExecutor.ExecuteListAsync<{typeName}>(GraphQLClient, queryBuilder, cancellationToken)";
        }

        if (type.IsList() && type.GetType_().OfType.IsInterface())
        {
            // Lists of interface values are returned as ids and reconstructed
            // lazily as their wrapper class via the node lookup, mirroring the
            // list-of-objects path above.
            var typeName = type.GetType_().OfType.GetTypeName();
            return $"""
                (await QueryExecutor.ExecuteListAsync<Id>(GraphQLClient, queryBuilder, cancellationToken))
                    .Select(id =>
                        ({typeName})
                            new {typeName}Wrapper(
                                QueryBuilder.Builder()
                                    .Select("node", ImmutableList.Create<Argument>(new Argument("id", new StringValue(id.Value))))
                                    .Select("... on {typeName}"),
                                GraphQLClient
                            )
                    )
                    .ToArray()
                """;
        }

        // An interface value is returned as its concrete wrapper class (the
        // interface itself is abstract and cannot be instantiated). The wrapper
        // is positioned at the current query builder, just like an object.
        if (type.IsInterface())
        {
            return $"new {field.Type.GetTypeName()}Wrapper(queryBuilder, GraphQLClient)";
        }

        return $"new {field.Type.GetTypeName()}(queryBuilder, GraphQLClient)";
    }

    private object RenderArgumentBuilder(Field field)
    {
        if (field.Args.Length == 0)
        {
            return string.Empty;
        }

        var builder = new StringBuilder("var arguments = ImmutableList<Argument>.Empty;");
        builder.Append('\n');

        var requiredArgs = field.RequiredArgs();
        if (requiredArgs.Any())
        {
            builder
                .Append("arguments = arguments.")
                .Append(
                    string.Join(
                        ".",
                        requiredArgs.Select(arg =>
                            $$"""Add(new Argument("{{arg.Name}}", {{RenderArgumentValue(arg)}}))"""
                        )
                    )
                )
                .Append(';');
            builder.Append('\n');
        }

        var optionalArgs = field.OptionalArgs();
        if (optionalArgs.Any())
        {
            optionalArgs
                .Aggregate(
                    builder,
                    (sb, arg) =>
                    {
                        var varName = arg.GetVarName();
                        return sb.Append(
                                $"""if ({varName} is {GetNormalizedTypeName(arg)} {varName}_)"""
                            )
                            .Append("{\n")
                            .Append(
                                $$"""    arguments = arguments.Add(new Argument("{{arg.Name}}", {{RenderArgumentValue(arg, addVarSuffix: true)}}));"""
                            )
                            .Append("}\n");
                    }
                )
                .Append("\n");
        }

        return builder.ToString();
    }

    internal static string RenderArgumentValue(
        InputValue arg,
        bool addVarSuffix = false,
        bool asProperty = false
    )
    {
        var argName = arg.GetVarName();
        if (addVarSuffix)
        {
            argName = $"{argName}_";
        }

        if (asProperty)
        {
            argName = Formatter.FormatProperty(argName);
        }

        if (arg.Type.IsScalar())
        {
            var type = arg.Type.GetTypeName();
            var token = SyntaxFacts.GetKeywordKind(type);

            switch (token)
            {
                case SyntaxKind.StringKeyword:
                    return $"new StringValue({argName})";
                case SyntaxKind.BoolKeyword:
                    return $"new BooleanValue({argName})";
                case SyntaxKind.IntKeyword:
                    return $"new IntValue({argName})";
                case SyntaxKind.FloatKeyword:
                    return $"new FloatValue({argName})";
                default:
                    // // a type but needs to convert into id value before sending it.
                    if (type.EndsWith("Id") && !string.Equals(arg.Name, "id"))
                    {
                        return $"new IdValue<{type}>({argName})";
                    }

                    // Id type.
                    return $"new StringValue({argName}.Value)";
            }
        }

        if (arg.Type.IsEnum())
        {
            return $"new StringValue({argName}.ToString())";
        }

        if (arg.Type.IsInputObject())
        {
            return $"new ObjectValue({argName}.ToKeyValuePairs())";
        }

        if (arg.Type.IsList())
        {
            var tr = arg.Type.GetType_().OfType.GetType_();

            if (tr.IsScalar())
            {
                var type = tr.GetType_().GetTypeName();
                var token = SyntaxFacts.GetKeywordKind(type);

                var value = token switch
                {
                    SyntaxKind.StringKeyword => "new StringValue(v)",
                    SyntaxKind.IntKeyword => "new IntValue(v)",
                    SyntaxKind.FloatKeyword => "new FloatValue(v)",
                    SyntaxKind.BoolKeyword => "new BooleanValue(v)",
                    _ => (type.EndsWith("Id") && !string.Equals(arg.Name, "id"))
                        ? $"new IdValue<{type}>(v)"
                        : "new StringValue(v.Value)",
                };

                return $"new ListValue({argName}.Select(v => {value} as Value).ToList())";
            }

            if (tr.IsInputObject())
            {
                return $"new ListValue({argName}.Select(v => new ObjectValue(v.ToKeyValuePairs()) as Value).ToList())";
            }

            if (tr.IsEnum())
            {
                return $"new ListValue({argName}.Select(v => new StringValue(v.ToString()) as Value).ToList())";
            }

            throw new Exception(
                $"The type {tr.Describe_()} is not implemented as list value. This is a bug in the generator."
            );
        }

        throw new Exception($"The type {arg.Type.Describe_()} should not be enter here.");
    }

    private static string RenderQueryBuilder(Field field)
    {
        var builder = new StringBuilder("var queryBuilder = QueryBuilder.Select(");
        builder.Append($"\"{field.Name}\"");
        if (field.Args.Length > 0)
        {
            builder.Append(", arguments");
        }

        builder.Append(')');
        if (field.Type.IsList() && !field.Type.GetType_().OfType.IsLeaf())
        {
            builder.Append(".Select(\"id\")");
        }

        builder.Append(';');
        return builder.ToString();
    }

    public string RenderInterface(Type type)
    {
        var interfaceName = Formatter.FormatType(type.Name);
        var wrapperName = $"{interfaceName}Wrapper";

        var fields = type.Fields ?? Array.Empty<Field>();

        // Interfaces carry an engine-assigned id field; expose it through
        // IId<Id> so interface values can be passed wherever an id-bearing
        // value is expected (e.g. as IdValue arguments), and skip the explicit
        // id signature since IId<Id> already declares it.
        var hasId = fields.Any(f => f.Name == "id");
        var baseIface = hasId ? " : IId<Id>" : "";

        // The interface declares the field signatures.
        var interfaceSignatures = fields
            .Where(f => !(hasId && f.Name == "id"))
            .Select(field => RenderFieldSignature(field, type.Name));

        // The wrapper is an ordinary Object positioned (by whoever constructs it)
        // at the interface value in the query graph, so its methods build queries
        // exactly like a concrete object's methods. Rendering them through the
        // shared RenderFieldMethod guarantees the signatures match the interface.
        var wrapperMethods = fields.Select(field => RenderFieldMethod(field, type.Name));

        return $$"""
            {{RenderDocComment(type)}}
            [Interface]
            public interface {{interfaceName}}{{baseIface}}
            {
                {{string.Join("\n\n", interfaceSignatures)}}
            }

            /// <summary>
            /// Wrapper for the {{interfaceName}} interface.
            /// Used when receiving {{interfaceName}} instances (e.g. from other modules);
            /// the query builder is positioned at the interface value.
            /// </summary>
            public class {{wrapperName}}(QueryBuilder queryBuilder, GraphQLClient gqlClient) : Object(queryBuilder, gqlClient), {{interfaceName}}
            {
                {{string.Join("\n\n", wrapperMethods)}}
            }
            """;
    }
}
